version: '3.3'

services:
  elasticsearch:
    build:
        context: ./docker/elasticsearch
        dockerfile: Dockerfile
    volumes:
      - "./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"


  logstash:
    build:
        context: ./docker/logstash
        dockerfile: Dockerfile
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d

  kibana:
    build:
        context: ./docker/kibana
        dockerfile: Dockerfile

  curator:
    build:
        context: ./docker/curator
        dockerfile: Dockerfile
    volumes:
        - ./docker/curator/entrypoint.sh:/entrypoint.sh
        - ./docker/curator/curator_config:/curator_config
        - ./docker/curator/start-cron:/start-cron

  # backup:
  #   volumes:
  #     - "./docker/curator/start-cron:/usr/sbin/start-cron"
  #     - "./docker/curator/backup.sh:/backup.sh"
  #     - "./docker/curator/entrypoint.sh:/entrypoint.sh"
