version: '3.3'

volumes:
  data:
    driver: local


services:
  elasticsearch:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-elasticsearch:${REGISTRY_TAG}
    volumes:
      - data:/usr/share/elasticsearch/data
      - ./backup:/mount/backups/my_backup
    ports:
      - "9200:9200"


  logstash:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-logstash:${REGISTRY_TAG}
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./.env-files:/.env-files"
    ports:
      - "5000:5000"
      # - "514:5140/udp"
      - "1025:1025/udp"
      - "1026:1026/udp"

  kibana:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-kibana:${REGISTRY_TAG}
    ports:
      - "5601:5601"


  curator:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
    depends_on: ["elasticsearch"]
    env_file: .env
    volumes:
        - "./.env-files:/.env-files"
        - ./backup:/mount/backups/my_backup
    command: curator

  backup:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
    depends_on: ["elasticsearch"]
    env_file: .env
    volumes:
      - ./backup:/mount/backups/my_backup
      - "./.env:/.env"
      - "./.env-files/:/.env-files"
    command: backup
    depends_on:
      - elasticsearch
