version: '3.7'

services:
  elasticsearch:
    build:
      context: ./docker
      dockerfile: elasticsearch/Dockerfile
    environment:
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    volumes:
      - "./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"


  logstash:
    build:
      context: ./docker
      dockerfile: logstash/Dockerfile
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d
      - ./docker/logstash/patterns:/usr/share/logstash/pipeline/patterns

  kibana:
    build:
      context: ./docker
      dockerfile: kibana/Dockerfile
    volumes:
        - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  curator:
    build:
      context: .
      dockerfile: docker/main/Dockerfile
    volumes:
        - ./services:/services
        - ./docker/main/entrypoint.sh:/entrypoint.sh
        - ./conf:/conf
        - ./docker/utils.sh:/utils.sh

  stunnel:
    volumes:
      - ./conf/stunnel.conf:/etc/stunnel/stunnel.conf
      - ./docker/utils.sh:/utils.sh
      - ./docker/main/entrypoint.sh:/entrypoint.sh
