version: '2'

networks:
  docker_elk:
    driver: bridge

volumes:
  data:
    driver: local
  test-log:
    driver: local


services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
    volumes:
      - "data:/usr/share/elasticsearch/data"


  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch


  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    logging:
      driver: none


  # logspout:
  #   image: bekt/logspout-logstash
  #   restart: on-failure
  #   environment:
  #     ROUTE_URIS: logstash://logstash:5000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - docker_elk

  filebeat:
    depends_on: ["logstash"]
    build: filebeat/
    volumes:
      - ./filebeat/config/filebeat.yml:/filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /var/log/auth.log/:/var/log/auth.log
    networks:
      - docker_elk
    logging:
      driver: none
