version: "3.7"

volumes:
  data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.5.9.0/24

services:
  elasticsearch:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-elasticsearch:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    volumes:
      - data:/usr/share/elasticsearch/data
      - ./backup:/mount/backups/my_backup
    environment:
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
    ports:
      - "127.0.0.1:9200:9200"

  logstash:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-logstash:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-logstash
    depends_on: ["elasticsearch"]
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./.env-files:/.env-files"
      - ./output:/usr/share/logstash/output/
    ports:
      - "514:5140/udp"
      - "1026:1026"
      - "1025:1025"

  kibana:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-kibana:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-kibana
    ports:
      - "127.0.0.1:5601:5601"

  curator:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-main:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-curator
    depends_on: ["elasticsearch"]
    env_file: .env
    stop_signal: SIGUSR1
    volumes:
      - "./.env-files:/.env-files"
      - ./backup:/mount/backups/my_backup
      - ./output:/usr/share/logstash/output/
    command: curator

  stunnel:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-main:${VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-stunnel
    env_file: .env
    volumes:
      - ./.env-files/:/.env-files
    command: stunnel
    ports:
      - "9201:9200"
