version: "3.7"

volumes:
  "9200":
    name: "9200"
  "grafana":
    name: "grafana"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.5.9.0/24

services:
  elasticsearch:
    image: ${REGISTRY_URL}/vertis-logserver-elasticsearch:${VERSION}
    container_name: vertis-logserver-elasticsearch
    volumes:
      - 9200:/usr/share/elasticsearch/data
      - ./backup:/mount/backups/my_backup
    environment:
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "127.0.0.1:9200:9200"

  logstash:
    image: ${REGISTRY_URL}/vertis-logserver-logstash:${VERSION}
    container_name: vertis-logserver-logstash
    depends_on: ["elasticsearch"]
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./.env-files:/.env-files"
      - ./output:/usr/share/logstash/output/
    ports:
      - "514:5140/udp"
      - "1026:1026"
      - "1025:1025"

  kibana:
    image: ${REGISTRY_URL}/vertis-logserver-kibana:${VERSION}
    container_name: vertis-logserver-kibana
    ports:
      - "127.0.0.1:5601:5601"

  grafana:
    image: grafana/grafana:7.5.2
    env_file: .env
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

  curator:
    image: ${REGISTRY_URL}/vertis-logserver-main:${VERSION}
    container_name: vertis-logserver-curator
    depends_on: ["elasticsearch"]
    env_file: .env
    stop_signal: SIGUSR1
    volumes:
      - "./.env-files:/.env-files"
      - ./backup:/mount/backups/my_backup
      - ./output:/usr/share/logstash/output/
    command: curator

  stunnel:
    image: ${REGISTRY_URL}/vertis-logserver-main:${VERSION}
    container_name: vertis-logserver-stunnel
    env_file: .env
    volumes:
      - ./.env-files/:/.env-files
    command: stunnel
    ports:
      - "9201:9200"
