version: '3.3'

services:
  elasticsearch:
    build:
      context: ./docker
      dockerfile: /elasticsearch/Dockerfile
    volumes:
      - "./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"


  logstash:
    build:
      context: ./docker
      dockerfile: /logstash/Dockerfile
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d

  kibana:
    build:
      context: ./docker
      dockerfile: /kibana/Dockerfile
    volumes:
        - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  curator:
    build:
      context: ./docker
      dockerfile: /curator/Dockerfile
    volumes:
        - ./docker/curator/entrypoint.sh:/entrypoint.sh
        - ./docker/curator/curator_config:/curator_config
        - ./docker/curator/start-cron:/start-cron
        - ./docker/utils.sh:/utils.sh

  backup:
    volumes:
      - ./docker/curator/start-cron:/usr/sbin/start-cron
      - ./docker/curator/backup.sh:/backup.sh
      - ./docker/utils.sh:/utils.sh
      - ./docker/curator/entrypoint.sh:/entrypoint.sh

  stunnel:
    build:
      context: ./docker
      dockerfile: /stunnel/Dockerfile
    volumes:
      - ./docker/stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
      - ./docker/utils.sh:/utils.sh
      - ./docker/stunnel/entrypoint.sh:/entrypoint.sh
