version: '3.3'

volumes:
  data:
    driver: local
  backup:
    driver: local


services:
  elasticsearch:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-elasticsearch:${REGISTRY_TAG}
    volumes:
      - "data:/usr/share/elasticsearch/data"
      - "backup:/mount/backups/my_backup"
    ports:
      - "9200:9200"


  logstash:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-logstash:${REGISTRY_TAG}
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./.env-files:/.env-files"
    ports:
      - "5000:5000"
      # - "514:5140/udp"
      - "1025:1025/udp"
      - "1026:1026/udp"

  kibana:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-kibana:${REGISTRY_TAG}
    ports:
      - "5601:5601"


  curator:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
    depends_on: ["elasticsearch"]
    env_file: .env
    volumes:
        - "./.env-files:/.env-files"
        - "backup:/mount/backups/my_backup"
    command: start-cron --user root "${CURATOR_CRON}"

  # backup:
  #   image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
  #   depends_on: ["elasticsearch"]
  #   env_file: .env
  #   volumes:
  #     - "backup:/mount/backups/my_backup"
  #     - "./.env:/.env"
  #     - "./.env-files/id_rsa:/home/myvertis/.ssh/id_rsa"
  #     - "./.env-files/id_rsa.pub:/home/myvertis/.ssh/id_rsa.pub"
  #     - "./.env-files/known_hosts:/home/myvertis/.ssh/known_hosts"
  #   entrypoint: ./entrypoint.sh backup
  #   command: start-cron --user linux_backup "${BACKUP_CRON}"
  #   depends_on:
  #     - elasticsearch
