version: '3'

volumes:
  data:
    driver: local

services:
    # src:                                                          # prod only
    #   image: ${COMPOSE_PROJECT_NAME}-src                          # prod only
    #   volumes:                                                    # prod only
    #     - "/src"                                                  # prod only
    #   command: ["true"]                                           # prod only

  elasticsearch:
    build:                                                        # dev only
        context: ./docker/elasticsearch                           # dev only
        dockerfile: Dockerfile                                    # dev only
    image: ${COMPOSE_PROJECT_NAME}-elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      pack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    volumes:
      - "data:/usr/share/elasticsearch/data"
    # logging:                                                    # prod only
      # driver: none                                              # prod only


  logstash:
    build:                                                        # dev only
        context: ./docker/logstash                                # dev only
        dockerfile: Dockerfile                                    # dev only
    image: ${COMPOSE_PROJECT_NAME}-logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d             # dev only
      - "./.env-files:/.env-files"
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    # logging:                                                    # prod only
      # driver: none                                              # prod only


  kibana:
    build:                                                        # dev only
        context: ./docker/kibana                                  # dev only
        dockerfile: Dockerfile                                    # dev only
    image: ${COMPOSE_PROJECT_NAME}-kibana
    volumes:
      - ./docker/kibana/config/:/etc/kibana/                             # dev only
      - "./.env-files:/.env-files"
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    # logging:                                                    # prod only
      # driver: none                                              # prod only
