version: '2'

volumes:
  data:
    driver: local
  test-log:
    driver: local


services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      pack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    volumes:
      - "data:/usr/share/elasticsearch/data"


  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./certificate.crt/:/certificate.crt
      - ./certificate.key/:/certificate.key
      - ./ca.crt/:/ca.crt
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch


  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
      - ./certificate.crt/:/tmp/certificate.crt
      - ./certificate.key/:/tmp/certificate.key
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
