version: '3.3'

volumes:
  data:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_RANGE}


services:
  elasticsearch:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-elasticsearch:${REGISTRY_TAG}
    volumes:
      - data:/usr/share/elasticsearch/data
      - ./backup:/mount/backups/my_backup
    ports:
      - 443:443
      - "127.0.0.1:9200:9200"

  logstash:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-logstash:${REGISTRY_TAG}
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./.env-files:/.env-files"
    ports:
      - "5000:5000"
      - "514:5140/udp"
      - "1025:1025/udp"
      - "1026:1026/udp"

  kibana:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-kibana:${REGISTRY_TAG}
    ports:
      - "5601:5601"


  curator:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
    depends_on: ["elasticsearch"]
    env_file: .env
    environment:
      CURATOR_CRON : '\10 \20 \* \* \* /usr/local/bin/curator --config /curator_config/curator.yml /curator_config/action.yml >> /var/log/cron.log 2>&1'
    volumes:
        - "./.env-files:/.env-files"
        - ./backup:/mount/backups/my_backup
    command: curator

  backup:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-curator:${REGISTRY_TAG}
    depends_on: ["elasticsearch"]
    env_file: .env
    environment:
      BACKUP_CRON : '\40 \20 \* \* \* /bin/bash /backup.sh >> /var/log/cron.log 2>&1'
    volumes:
      - ./backup:/mount/backups/my_backup
      - "./.env-files/:/.env-files"
    command: backup

  stunnel:
    image: ${REGISTRY_URL}/${REGISTRY_PREFIX}/${COMPOSE_PROJECT_NAME}-stunnel:${REGISTRY_TAG}
    env_file: .env
    volumes:
      - ./.env-files/:/.env-files
    ports:
      - "9201:9200"
