actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 40 days (based on index name), for winlogbeat-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^winlogbeat-"
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${BACKUP_RETENTION_DAYS}

  2:
    action: delete_indices
    description: >-
      Delete indices older than 40 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^filebeat-"
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${BACKUP_RETENTION_DAYS}
  3:
    action: delete_indices
    description: >-
      Delete indices older than 40 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^logstash-"
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${BACKUP_RETENTION_DAYS}
  4:
    action: delete_indices
    description: >-
      Delete indices older than 40 days (based on index name), for auditbeat-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^auditbeat-"
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${BACKUP_RETENTION_DAYS}
  5:
    action: delete_indices
    description: >-
      Delete indices older than 7 days (based on index name), for metricbeat-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^metricbeat-"
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${METRICBEAT_BACKUP_RETENTION_DAYS}
  6:
    action: snapshot
    description: >-
      Snapshot selected indices to 'repository' with the snapshot name or name
      pattern in 'name'.  Use all other options as assigned
    options:
      repository: my_backup
      name: "curator-%Y-%m-%d-%H-%M-%S"
      ignore_unavailable: True
      wait_for_completion: True
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^filebeat-|^winlogbeat-|^logstash-|^auditbeat-|.kibana"
      - filtertype: pattern
        kind: prefix
        value: metric-
        exclude: True
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 0
  7:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 40 days
      (based on creation_date), for 'curator-' prefixed snapshots.
    options:
      repository: my_backup
      ignore_empty_list: True
      disable_action: False
    filters:
      - filtertype: pattern
        kind: prefix
        value: "^curator-"
        exclude:
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: ${BACKUP_RETENTION_DAYS}
